config: 
  - runtime: node:18
  - environment: terrificproject
    
stages:
  - name: Build App And Push To Repository
    when: repo.branch == "main"
    commands:
      - "docker build -t terrificci/projectexample:latest ."
      - "docker push terrificci/projectexample:latest"
  - name: Deploy App
    when: repo.branch == "main"
    ssh: 
      - server: "terrificserver"
        copy: 
          - source: "docker-compose.yaml"
            destination: "/home/vannila/terrificdeployment"
        commands:
          - "cd /home/vannila/terrificdeployment"
          - "docker compose up -d "
          
    
